[package]
name = "shedos-screensaver-wayland"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Wayland-native fullscreen overlay renderer (wlr-layer-shell + wlr-shm)"

[dependencies]
shedos-prompt-ui.workspace = true
shedos-screensaver-core.workspace = true
smithay-client-toolkit.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr.workspace = true
fontdue.workspace = true
image.workspace = true
