[package]
name = "shedos-screensaver-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "CLI binary for shedos-screensaver"

[[bin]]
name = "shedos-screensaver"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
crossterm.workspace = true
libc.workspace = true
pam.workspace = true
rand.workspace = true
rand_chacha.workspace = true
serde.workspace = true
shedos-prompt-ui.workspace = true
shedos-screensaver-core.workspace = true
shedos-screensaver-i18n.workspace = true
shedos-screensaver-logos.workspace = true
shedos-screensaver-effects.workspace = true
shedos-screensaver-tty.workspace = true
shedos-screensaver-wayland.workspace = true
shedos-screensaver-audio.workspace = true
toml.workspace = true
