[package]
name = "shedos-screensaver-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Pipewire FFT audio source for shedos-screensaver"

[dependencies]
shedos-screensaver-core.workspace = true
cpal.workspace = true
realfft.workspace = true
